#!/bin/bash -e

docker run \
    --cidfile=cid \
    -e VERSION=$VERSION \
    -e SHA=$SHA \
    -v $PWD:/go/src/github.com/etcd-io/zetcd:ro \
    -w /go/src/github.com/etcd-io/zetcd \
    golang:1.17.2-alpine \
    /bin/sh -x -c scripts/release-binary

docker rm $( cat cid )
rm cid
